"""Golden regression: a Quarkus/Hibernate-6/Jakarta-complete repo (Keycloak shape).

Reproduces the false-positive cluster found on real Keycloak (Quarkus 3.x,
Hibernate ORM 6.2.13, Jakarta migration complete) that made migrate-check emit
`readiness 0/100`, a phantom `hibernate_rewrite` headline, and a `boot3` dimension
marked applicable without any Spring. Every assertion here maps to one of the nine
bugs fixed in v1.65.0; if any regresses, this fails.
"""
from __future__ import annotations

from pathlib import Path

from sourcecode.migrate_check import run_migrate_check


def _write(root: Path, rel: str, content: str) -> None:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")


def _build_keycloak_like(root: Path) -> list[str]:
    # Quarkus + Hibernate ORM 6.2.13 — NO Spring anywhere.
    _write(root, "pom.xml",
           "<project>\n"
           "  <properties>\n"
           "    <quarkus.platform.version>3.33.1.1</quarkus.platform.version>\n"
           "    <hibernate-orm.version>6.2.13.Final</hibernate-orm.version>\n"
           "  </properties>\n"
           "  <dependencies>\n"
           "    <dependency><groupId>org.hibernate.orm</groupId>\n"
           "      <artifactId>hibernate-core</artifactId>\n"
           "      <version>${hibernate-orm.version}</version></dependency>\n"
           "  </dependencies>\n"
           "</project>\n")

    files: list[str] = []

    # ── Product (main) code ──────────────────────────────────────────────────
    # Jakarta-complete JPA entity + a Hibernate annotation (so Hibernate detected).
    f = "model/src/main/java/org/keycloak/models/UserEntity.java"
    _write(root, f,
           "import jakarta.persistence.Entity;\n"
           "import jakarta.persistence.Id;\n"
           "import org.hibernate.annotations.BatchSize;\n"
           "@Entity public class UserEntity { @Id String id; }\n")
    files.append(f)

    # Permanent JDK javax.* (allowlist) — must NOT count as jakarta debt (BUG #3).
    f = "common/src/main/java/org/keycloak/common/XmlUtil.java"
    _write(root, f,
           "import javax.xml.parsers.DocumentBuilder;\n"
           "import javax.crypto.Cipher;\n"
           "import javax.naming.directory.DirContext;\n"
           "public class XmlUtil {}\n")
    files.append(f)

    # One genuine main JDK-17 finding (SecurityManager) — the only real blocker.
    f = "saml-core/src/main/java/org/keycloak/saml/SecurityActions.java"
    _write(root, f,
           "public class SecurityActions {\n"
           "  void go() { SecurityManager sm = System.getSecurityManager(); }\n"
           "}\n")
    files.append(f)

    # Best-practice hygiene (Date) — must not sink any dimension (BUG #6).
    f = "services/src/main/java/org/keycloak/TimeUtil.java"
    _write(root, f, "import java.util.Date;\npublic class TimeUtil {}\n")
    files.append(f)

    # ── Autogenerated SCIM code: javax.annotation.Generated (BUG #7) ──────────
    f = "federation/ipatuura/src/main/java/org/keycloak/scim/SCIMUser.java"
    _write(root, f,
           "import javax.annotation.Generated;\n"
           "@Generated(\"scim-codegen\") public class SCIMUser {}\n")
    files.append(f)

    # ── Test-framework module (src/main, but test infra): sun.* (BUG #8) ──────
    # Uses a genuinely-encapsulated JDK-internal import (sun.misc.*) so MIG-011
    # fires but is bucketed as test (non-blocking). Note: com.sun.net.httpserver
    # would NOT fire post-v1.69.0 (BUG #1 — it is exported unconditionally).
    f = "test-framework/core/src/main/java/org/keycloak/testframework/InternalSupplier.java"
    _write(root, f,
           "import sun.misc.BASE64Encoder;\n"
           "public class InternalSupplier {}\n")
    files.append(f)

    # ── Test fixture web.xml with the Java EE namespace (BUG #8) ──────────────
    _write(root,
           "testsuite/integration-arquillian/tests/base/src/test/resources/adapter-test/web.xml",
           '<web-app xmlns="http://java.sun.com/xml/ns/javaee" version="3.0"></web-app>\n')

    return files


def _run(tmp_path: Path):
    files = _build_keycloak_like(tmp_path)
    return run_migrate_check(files, tmp_path)


def test_no_phantom_hibernate_blocker(tmp_path: Path) -> None:
    # BUG #1: Hibernate 6.2.13 resolved → 5→6 axis N/A, no headline.
    report = _run(tmp_path)
    assert report.headline_blocker != "hibernate_rewrite"
    assert report.headline_blocker is None
    assert report.hibernate.effective_version == "6.2.13.Final"
    assert report.hibernate.migration_applicable is False
    assert report.applicable_dimensions["hibernate"]["applicable"] is False


def test_boot3_not_applicable_without_spring(tmp_path: Path) -> None:
    # BUG #2: no Spring anywhere → Boot3 dimension is N/A.
    report = _run(tmp_path)
    assert report.spring_present is False
    assert report.applicable_dimensions["boot3"]["applicable"] is False


def test_jakarta_readiness_high(tmp_path: Path) -> None:
    # BUG #3 + #7: permanent javax.* not counted; Generated downgraded → ≥ 95.
    report = _run(tmp_path)
    assert report.jakarta_readiness >= 95


def test_blocking_count_excludes_test_fixtures(tmp_path: Path) -> None:
    # BUG #8: test-framework sun.* and test web.xml excluded → only the real
    # main SecurityManager remains.
    report = _run(tmp_path)
    assert report.blocking_count <= 6
    assert report.non_blocking["count"] >= 2  # sun.* + web.xml at least
    # No jakarta finding from the test web.xml leaked into main jakarta scoring.
    main_jakarta = [f for f in report.findings
                    if f.code_context == "main" and f.migration_target == "jakarta"
                    and f.severity in ("critical", "high")]
    assert main_jakarta == []


def test_readiness_not_zero(tmp_path: Path) -> None:
    # BUG #4: a modernized repo never reports the misleading 0 headline.
    report = _run(tmp_path)
    assert report.readiness_score >= 70


def test_best_practice_does_not_sink_dimension(tmp_path: Path) -> None:
    # BUG #6: java.util.Date is hygiene, surfaced separately.
    report = _run(tmp_path)
    assert report.hygiene_findings >= 1


def test_generated_annotation_is_low_and_bucketed(tmp_path: Path) -> None:
    # BUG #7: javax.annotation.Generated → low severity, symbol-specific text,
    # classified as generated (non-blocking).
    report = _run(tmp_path)
    gen = [f for f in report.findings if f.rule_id == "MIG-006"]
    assert gen, "expected the javax.annotation.Generated finding"
    g = gen[0]
    assert g.severity == "low"
    assert "Generated" in g.explanation
    assert "@PostConstruct" not in g.explanation
    assert g.code_context == "generated"
